### ISSUE TITLE
Question Of 1.18.1 Estimated release time

### ISSUE THREAD

**Issue by Thingw31** [CorgiTaco-MC/Block-Swap#20]
Uh i dont know how to tag things, but just curious on the 1.18.1 block swap version, making a modpack with my friends and ik blockswap is somthing we are intested in but its just on base 1.18 Right now

**Comment by CorgiTaco** [comment]
It exists? 
Fabric: https://www.curseforge.com/minecraft/mc-mods/block-swap-fabric/files
Forge: https://www.curseforge.com/minecraft/mc-mods/block-swap/files
