### ISSUE TITLE
1.18.2?

### ISSUE THREAD

**Issue by Nekkok** [CorgiTaco-MC/Block-Swap#23]
I just wanted to know how is the update going, if any. I really love this mod and is an essential to me. Please, no pressure! Just asking, thank you so much : )

**Comment by Reshy** [comment]
I would appreciate this, it's useful for removing certain world generation features from mods without extensive configs.

**Comment by forthwist** [comment]
Sorta piling on here--I didn't realize how reliant I'd become on this mod until it wasn't there for my pack update. It's so straightforward and immensely handy.

**Comment by CorgiTaco** [comment]
Fabric 1.18.2: https://www.curseforge.com/minecraft/mc-mods/block-swap-fabric/files/3775381

Forge 1.18.2: https://www.curseforge.com/minecraft/mc-mods/block-swap/files/3775380

(Still under review so links might fail, come back later if they do)

**Comment by Nekkok** [comment]
I would like to thank you for reading your community feedback. I don't want to sound complacent, but feels very nice to be heard. Love your work and your commitment, big thanks : )

**Comment by forthwist** [comment]
Oh man, hero!  Thanks for this update 💛
