### ISSUE TITLE
[Bug]: There is no config

### ISSUE THREAD

**Issue by riley-9054** [CorgiTaco-MC/Block-Swap#26]
### Minecraft Version

1.18.2

### Block Swap Version

1.0.1

### Mod Loader

Forge

### Mod Loader Version

40.1.79

### Bug Severity

Major

### What happened?

I downloaded blow swap, put it in my mods folder, ran the game so it could create the proper folders and whatnot that it needed, and then closed the game. when i checking in the config file to start replacing blocks, there was no file or folder for block swap.
even after installing cloth config api, when i went to block swap in the mods list in-game the config button for it was greyed out.
I don't want to load into a world with the mod since after reading some of the bug reports i'm afraid it will ruin my world by replacing dirt with diamonds

### latest.log

[latest.log](https://github.com/CorgiTaco/Block-Swap/files/9933066/latest.log)

**Comment by CorgiTaco** [comment]
Config loads when loading into a world. So make a new world to ensure you dont break an existing one
