### ISSUE TITLE
Replacing a block with another that emits light does not update light

### ISSUE THREAD

**Issue by gglobensky** [CorgiTaco-MC/Block-Swap#4]
If you replace, for example, iron ore with shroomlight, you will see that the block will need to be manually updated (punching a block next to it) for it to start emitting light.

I don't know if that's in the scope of this mod but it'd be nice to be able to add light emitting blocks that way.

**Comment by CorgiTaco** [comment]
Should be fixed in latest! Try this: https://www.curseforge.com/minecraft/mc-mods/block-swap

**Comment by CorgiTaco** [comment]
And let me know if it works or not!

**Comment by gglobensky** [comment]
Wow nice I will test this!

**Comment by CorgiTaco** [comment]
did it work?

**Comment by gglobensky** [comment]
I confirm in the use case I told you about that it indeed worked.

Thanks a lot
